name: AWS Deploy Using Role

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::054276329279:role/github-actions-oidc-role
          aws-region: us-east-1

      - name: Confirm assumed role identity
        run: |
          aws sts get-caller-identity


    